#!/usr/bin/env bash
# Write nginx snippet for /feedback/ and include it in the existing PUBLIC_HOST 443 vhost.
# Does not replace location / or other apps' prefixes.
#
#   sudo bash deploy/configure-nginx.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/deploy/.env}"

run_root() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

load_env_file() {
  local file=$1
  [[ -f "$file" ]] || return 1
  local line key value
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line//$'\r'/}"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      key="${BASH_REMATCH[1]}"
      value="${BASH_REMATCH[2]}"
      value="${value#\"}"; value="${value%\"}"
      value="${value#\'}"; value="${value%\'}"
      export "$key=$value"
    fi
  done < "$file"
}

normalize_path() {
  local value="${1:-}"
  value="/${value#/}"
  echo "${value%/}"
}

write_snippet() {
  local base=$1 port=$2
  cat <<EOF
# Generated by deploy/configure-nginx.sh — do not edit in place.
# Recreate with: sudo bash deploy/configure-nginx.sh

location = ${base} { return 301 ${base}/; }

location ${base}/ {
    proxy_pass http://127.0.0.1:${port}${base}/;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 120s;
    proxy_send_timeout 120s;
}
EOF
}

insert_include() {
  local site=$1 snippet=$2
  local py=""
  if command -v python3 >/dev/null 2>&1; then
    py="python3"
  elif command -v python >/dev/null 2>&1; then
    py="python"
  else
    echo "    python not found; add this line inside the listen 443 server:" >&2
    echo "      include ${snippet};" >&2
    return 1
  fi
  $py - "$site" "$snippet" <<'PY'
import sys
from pathlib import Path

site = Path(sys.argv[1])
snippet = sys.argv[2]
include_line = f"    include {snippet};\n"
text = site.read_text(encoding="utf-8")
if snippet in text:
    print("    include already present")
    sys.exit(0)
lines = text.splitlines(keepends=True)
out = []
inserted = False
in_443 = False
for line in lines:
    out.append(line)
    stripped = line.strip()
    if not inserted and "listen 443" in stripped:
        in_443 = True
    if in_443 and not inserted and stripped.startswith("ssl_certificate_key"):
        out.append("\n" + include_line)
        inserted = True
        in_443 = False
if not inserted:
    sys.exit(2)
site.write_text("".join(out), encoding="utf-8")
print("    inserted include into", site)
PY
}

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Error: missing $ENV_FILE — run bash start.sh first or copy deploy/.env.example." >&2
  exit 1
fi

load_env_file "$ENV_FILE"

PUBLIC_HOST="${PUBLIC_HOST#https://}"
PUBLIC_HOST="${PUBLIC_HOST#http://}"
PUBLIC_HOST="${PUBLIC_HOST%/}"
PUBLIC_HOST="${PUBLIC_HOST:-client-demo.inapp.com}"
HOST_PORT="${HOST_PORT:-14020}"
APP_BASE="$(normalize_path "${APP_BASE_PATH:-/feedback}")"
SNIPPET_PATH="${NGINX_SNIPPET:-/etc/nginx/snippets/dcf-feedback.conf}"
SITE_NAME="${NGINX_SITE_NAME:-$PUBLIC_HOST}"
SITE_FILE="/etc/nginx/sites-available/${SITE_NAME}"

echo "==> Writing nginx snippet ${SNIPPET_PATH}"
echo "    Host    : ${PUBLIC_HOST}"
echo "    App     : 127.0.0.1:${HOST_PORT}${APP_BASE}/"

if ! command -v nginx >/dev/null 2>&1; then
  if ! command -v apt-get >/dev/null 2>&1; then
    echo "Error: nginx is not installed and apt-get is not available." >&2
    exit 1
  fi
  echo "==> Installing nginx..."
  run_root apt-get update -y
  run_root apt-get install -y nginx
fi

TMP_SNIP="$(mktemp)"
write_snippet "$APP_BASE" "$HOST_PORT" >"$TMP_SNIP"
run_root mkdir -p "$(dirname "$SNIPPET_PATH")"
run_root cp "$TMP_SNIP" "$SNIPPET_PATH"
rm -f "$TMP_SNIP"

if [[ -f "$SITE_FILE" ]]; then
  TMP_SITE="$(mktemp)"
  run_root cat "$SITE_FILE" >"$TMP_SITE"
  if insert_include "$TMP_SITE" "$SNIPPET_PATH"; then
    run_root cp "$TMP_SITE" "$SITE_FILE"
  else
    echo "    Could not auto-insert include. Add this inside the listen 443 server in ${SITE_FILE}:" >&2
    echo "      include ${SNIPPET_PATH};" >&2
  fi
  rm -f "$TMP_SITE"
else
  echo "    Site file ${SITE_FILE} not found. Snippet is written; include it in your 443 vhost:"
  echo "      include ${SNIPPET_PATH};"
fi

echo "==> Testing nginx configuration..."
if ! run_root nginx -t; then
  echo "Error: nginx -t failed." >&2
  exit 1
fi

if command -v systemctl >/dev/null 2>&1; then
  if run_root systemctl is-active --quiet nginx; then
    run_root systemctl reload nginx
  else
    run_root systemctl start nginx
  fi
else
  run_root nginx -s reload 2>/dev/null || run_root nginx
fi

echo ""
echo "Nginx snippet installed:"
echo "  ${PUBLIC_SCHEME:-https}://${PUBLIC_HOST}${APP_BASE}/"
echo ""
echo "Re-run: sudo bash $ROOT/deploy/configure-nginx.sh"
